//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PblNet1.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giaodich
    {
        public int giaodichID { get; set; }
        public int userID { get; set; }
        public int theloaiID { get; set; }
        public decimal soluong { get; set; }
        public System.DateTime ngayGD { get; set; }
        public string Description { get; set; }
        public string diachi { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
    
        public virtual Theloai Theloai { get; set; }
        public virtual user user { get; set; }
    }
}
