//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PblNet1.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLTCEntities : DbContext
    {
        public QLTCEntities()
            : base("name=QLTCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Giaodich> Giaodiches { get; set; }
        public virtual DbSet<Ngansach> Ngansaches { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Theloai> Theloais { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
