//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PblNet1.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ngansach
    {
        public int NgansachID { get; set; }
        public int userID { get; set; }
        public Nullable<int> theloaiID { get; set; }
        public decimal Soluong { get; set; }
        public System.DateTime NgayBD { get; set; }
        public System.DateTime NgayKT { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
    
        public virtual Theloai Theloai { get; set; }
        public virtual user user { get; set; }
    }
}
