//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PblNet1.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theloai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Theloai()
        {
            this.Giaodiches = new HashSet<Giaodich>();
            this.Ngansaches = new HashSet<Ngansach>();
            this.Theloai1 = new HashSet<Theloai>();
        }
    
        public int theloaiID { get; set; }
        public string nameTL { get; set; }
        public string description { get; set; }
        public Nullable<int> ParenttheloaiID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Giaodich> Giaodiches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ngansach> Ngansaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Theloai> Theloai1 { get; set; }
        public virtual Theloai Theloai2 { get; set; }
    }
}
